### ISSUE TITLE
Migrate UI elements to the Any Any Size Class

### ISSUE THREAD

**Issue by ClintChil** [uffelman/Venty#1]
If you start building your storyboard in Compact width & Any height the UI elements only exist in that particular size class. Always start in Any Any and work your way smaller from there. 

You can fix it by installing the UI elements in the any any size class, reset the constraints and then remove them from the Compact any size class.

It's a little thing that can cause big problems later. I've seen projects where one team member is working in Any Any and the other in Compact Any.

http://stackoverflow.com/questions/27198661/why-storyboard-ui-elements-not-showing-on-uiviewcontroller-in-xcode-6

**Comment by uffelman** [comment]
Does that only apply if you might enable landscape mode or support iPads in the future?

**Comment by ClintChil** [comment]
I'll close this because it doesn't affect the user and it really isn't worth your time to fix on this project. I just wanted to help you learn the right way to use size classes.

**Comment by uffelman** [comment]
Thanks for the help!
